# Generated by Django 4.2.6 on 2023-10-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeId', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('subtitle', models.CharField(db_index=True, max_length=255)),
                ('authors', models.CharField(db_index=True, max_length=100)),
                ('publisher', models.CharField(db_index=True, max_length=100)),
                ('published_date', models.DateField()),
                ('distribution_expense', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumi_app.category')),
            ],
        ),
    ]
