# Generated by Django 4.2.6 on 2023-10-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
