# Generated by Django 4.2.6 on 2023-10-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumi_app', '0002_alter_book_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
