# Generated by Django 4.2.6 on 2023-10-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumi_app', '0003_alter_book_authors_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
